### ISSUE TITLE
1.6.0 came with Google trackers

### ISSUE THREAD

**Issue by HarriBuh** [zhanghai/MaterialFiles#1000]
Why on earth did you do this? I have been using your app as my standard file manager for years, because it was clean, simple and good looking.
Now this:

![Screenshot_20230828-101602](https://github.com/zhanghai/MaterialFiles/assets/123186113/7023baf0-f7ce-436a-b831-c7e1dac76e4b)
![Screenshot_20230828-101532](https://github.com/zhanghai/MaterialFiles/assets/123186113/2ef26cea-3ba6-4018-a8aa-1d3a5a917810)

Why do you need silent and filthy bug trackers when you could just continue to rely on issue reports here on GitHub? That's sad.

**Comment by zhanghai** [comment]
The Play version has always contained Firebase Analytics and Crashlytics and I never hid that, which you can see from the data security section on Play as well since long ago. There is also a privacy policy link in the Play version that clearly tells you I'm using Firebase Analytics and Crashlytics. I'm not sure why you are suddenly finding this out in the new version though.

You may have a different opinion on how necessary app adoption and crash metrics are important to developers, but it is actually the fastest way to ensure I find out problems fast, and it has helped me a lot before, and much faster than a very small portion of people creating issues on GitHub - by the time they do that I might have went to sleep with a new release that crashes the app for a vast amount of users. I feel a bit more pragmatic towards this kind of thing so this feels like some necessary evil to me. After all, it only collects crash reports and an ID to disambiguate all the devices.

If you want to opt out of Firebase Analytics and Crashlytics, you can use the F-Droid version which is built by F-Droid server and only with fully open source components, which means free of Firebase Analytics and Crashlytics as well. I hope this may be helpful to you.

**Comment by zhanghai** [comment]
Yes. F-Droid build is out of my control and has significant delays, so when I publish releases I publish the same APK to GitHub and Play.

**Comment by joshcangit** [comment]
> Yes. F-Droid build is out of my control and has significant delays

If you're not publishing updates to F-Droid, then who is?
