### ISSUE TITLE
Option to opt-out of analytics and consider another build

### ISSUE THREAD

**Issue by cohesive-flight** [zhanghai/MaterialFiles#1012]
Since Firebase is being used in the Github version, an option to opt-out of analytics would be nice. I know the F-Droid build is available, but I prefer getting an app from its source.

As an alternative, please consider making an additional build that's Google-free onto Github, similar to F-Droid's, but signed with your own keys. I've seen other app developers do this, where they publish a Playstore version, and a Google-free version of their apps onto Github, while also having an F-Droid build available. I'd prefer this over an opt-out option since it wouldn't have any Firebase libraries in the first place, and would have quicker updates (it could also contain RAR support unlike F-Droid's build).

**Comment by zhanghai** [comment]
You can consider the F-Droid version official - I don't think there's point in me downloading the APK from F-Droid and re-uploading it again here.

And yes, the issue with the opt-out option is that the Firebase libraries are still bundled into the app, and a lot of people still don't like that. And even if I offer that opt-out option, I don't have confidence to keep it 100% working as intended, and I don't want to ever be blamed for Firebase still somewhat running when people opted out.

Regarding the RAR support - I'm currently working on porting [libarchive](https://github.com/libarchive/libarchive) to Android, so that there will be FOSS support (thus available in F-Droid version) for both RAR and RAR5, plus a bunch of other formats.

**Comment by zhanghai** [comment]
RAR 5 is now supported via libarchive (#735), and will be available in the next release. Note that encryption isn't supported by libarchive yet.

**Comment by amadeuskurisu02** [comment]
> And yes, the issue with the opt-out option is that the Firebase libraries are still bundled into the app, and a lot of people still don't like that. And even if I offer that opt-out option, I don't have confidence to keep it 100% working as intended, and I don't want to ever be blamed for Firebase still somewhat running when people opted out. Or the other way around, somehow I misconfigure and I lose crash-reporting etc from the majority of Play users by default.
> 

I understand your opinion. It's just unfortunate to have to wait several days or even weeks for essential fixes like with 1.7.1 to be builded without crashlytics and firebase. It's would've been much better to have crashlytics and firebase free verision builded and published simultaniously on this repo. If I'll find a bug, I'll report it and I'll send logs, I don't need crashlytics and firebase. On f-droid right now is 1.7.0 and I need to wait several days or even weeks for these essential fixes with 1.7.1 or delete app, install earlier version and reconfigure everything, cuz I didn't knew that 1.7.0 have bugs with theming.

**Comment by zhanghai** [comment]
I can share another recent example where having the crash reporting here was really helpful. I was able to identify the SFTP/SMB issue #1154 shortly after the release on GitHub and cancel the rollout on Play to tens of thousands of users. The first user comment about it came in more than 24 hours later and at that time I might have lost the ability to cancel the Play rollout.
