### ISSUE TITLE
Cannot add/remove file and folders in work profile

### ISSUE THREAD

**Issue by tleydxdy** [zhanghai/MaterialFiles#1207]
I wanted to move files between my work profile (created using island) and the main profile.
So I created a folder called "Main" in the work profile, then in the main profile's material files I select add storage>external storage>"work">"Main">use this folder . As expected I can now see the content in the Main folder of the work profile.
However, if I try to move files into the folder or create new file/folders, I get this error
![Screenshot_20240421-001350](https://github.com/zhanghai/MaterialFiles/assets/10610765/5f5bedcb-1285-467d-b3a7-da207d1a6785)
It seems that the user part "10" there was missing in some API calls or the API used does not understand work profiles and content url?

**Comment by zhanghai** [comment]
The error is thrown at [this line in Android framework](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/provider/DocumentsProvider.java;l=1131;drc=f81e11d51ca758037198249178ae86d2fb7b3792).

```java
        if (!mAuthority.equals(authority)) {
            throw new SecurityException(
                    "Requested authority " + authority + " doesn't match provider " + mAuthority);
        }
```

So the message does mean that the app requested the correct authority (`10@` is the Android way of specifying a different user for a content URI), but the system itself didn't handle this multi-user correctly.

This doesn't impact reads because `query()` and `openFile()` isn't using this problematic `callUnchecked()`, but other methods are using it and indeed not working for cross-user cases.

**Comment by tleydxdy** [comment]
would this mean the request was routed to the wrong documentprovider?

**Comment by zhanghai** [comment]
I don't think so. The `ExternalStroageProvider` running inside any user should always be named the same and for its current user. It's the user ID prefix that should be dropped but isn't.

To be specific, `ContextImpl` resolves the user-specific URI to a provider in the correct user [here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/app/ContextImpl.java;l=3670;drc=3d19fbcc09b1b44928639b06cd0b88f735cd988d):

```java
        protected IContentProvider acquireProvider(Context context, String auth) {
            return mMainThread.acquireProvider(context,
                    ContentProvider.getAuthorityWithoutUserId(auth),
                    resolveUserIdFromAuthority(auth), true);
        }
```

And most `ContentProvider` methods removes the user ID from the URI like [here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/ContentProvider.java;l=253;drc=31676f42531a42201de4050d3bf575de46236460):

```java
        public Cursor query(@NonNull AttributionSource attributionSource, Uri uri,
                @Nullable String[] projection, @Nullable Bundle queryArgs,
                @Nullable ICancellationSignal cancellationSignal) {
            uri = validateIncomingUri(uri);
            uri = maybeGetUriWithoutUserId(uri);
        }
```

But the same thing isn't happening in `DocumentsProvider.call()`, hence the problem, and it needs to be fixed in the platform.

**Comment by tleydxdy** [comment]
thanks for the analysis! I opened https://issuetracker.google.com/issues/335997046

**Comment by zhanghai** [comment]
Correction: The fix should actually probably be in `ContentProvider.Transport.call()` instead of `DocumentsProvider`, since all user IDs are removed in the `Transport`.
