### ISSUE TITLE
Cbz and zip icon

### ISSUE THREAD

**Issue by Solovertical** [zhanghai/MaterialFiles#1231]
Any reason why the cbz and zip icons are the same (ver 1.7.2), unlike before? Now its hard to differentiate between them.

**Comment by zhanghai** [comment]
All archive files share the same icon. Before 1.7.2 cbz files weren't properly recognized as archive files due to out of date MIME type information.

**Comment by FooIbar** [comment]
Ain't CBZs expected to have ebook icons?
They have the same icons as ZIPs because the mime type here was updated
https://github.com/zhanghai/MaterialFiles/blob/c44710e77775c518a2ea51ae0cf37f64fc61aaed/app/src/main/java/me/zhanghai/android/files/compat/MimeTypeMapCompat.kt#L173
but not here
https://github.com/zhanghai/MaterialFiles/blob/c44710e77775c518a2ea51ae0cf37f64fc61aaed/app/src/main/java/me/zhanghai/android/files/file/MimeTypeIcon.kt#L163

**Comment by zhanghai** [comment]
Thanks @FooIbar , you are right here, I somehow overlooked the change for CBR and CBZ mime type mapping (which I imported from AOSP) when doing the update.
