### ISSUE TITLE
[Enhancement] Bookmark folders within root

### ISSUE THREAD

**Issue by ayathedoggo** [zhanghai/MaterialFiles#1257]
Currently, the option to bookmark folders only appears in the app itself and not the other menu that is employed when viewing root folders.

I'd appreciate an option to select folders inside of root, to be accessible with one tap via the left menu.

One use case is to quickly access app's data in android/obb/com.google.youtube, for example.

I'd really love to see this feature added. Thank you for all the great work you do on this app

**Comment by zhanghai** [comment]
What do you mean by "the other menu"? I could always bookmark a folder when viewing it, by the action in the menu opened by the three dots in the top right corner.

**Comment by ayathedoggo** [comment]
At present, tapping + in Bookmarks opens Material Files. This has the option at the bottom to select a bookmark.

However, to access android/data, it launches a different interface which doesn't have any of the bookmarking capabilities.

One solution could be to include a "add custom path" for bookmarks, then have the bookmark launch the different interface in the folder specified.

**Comment by ayathedoggo** [comment]
Accident, not used to Github UI on mobile.

**Comment by zhanghai** [comment]
> However, to access android/data, it launches a different interface which doesn't have any of the bookmarking capabilities.

That different interface is a different system app that has access to Android/data. Android has restricted regular apps from accessing Android/data nowadays so that system app has to be used. Since this app can't access Android/data, there's no point in bookmarking a folder inside Android/data either. The closest you can get is add an Android/data shortcut and long press it to edit that shortcut and manually put in the path you want shortcut to.

**Comment by ayathedoggo** [comment]
"The closest you can get is add an Android/data shortcut and long press it to edit that shortcut and manually put in the path you want shortcut to."
How do I add this fabled Android/data shortcut? Thank you!

**Comment by ayathedoggo** [comment]
Oh, thank you so much! <3
