### ISSUE TITLE
support for `android.intent.action.OPEN_DOCUMENT_TREE`

### ISSUE THREAD

**Issue by farfromrefug** [zhanghai/MaterialFiles#1273]
I see in the manifest that you disabled it commenting it is not implemented.
Though the code for it exists.
Could that be enabled?

I think have half the answer as i tried to build with it enabled in the manifest. Now i tried to use it with my app and i got an url like this `content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDocuments`
And trying to use that uri with `android.net.Uri` gave me the error `Invalid URI`.
Is that normal? is that part of the reason why you disabled it?

Thanks

**Comment by zhanghai** [comment]
Yes, it's not implemented so you got that error.

**Comment by shawly** [comment]
As there any chance this gets implemented?
I am trying to use a sideloaded app on my Tolino Vision 6 (eReader) but the app fails to open a the file picker, since the ereader doesn't have any DocumentsUI app and sideloading the DocumentsUI app doesn't work. 
But Material Files works for the OPEN_DOCUMENT intent, I hoped that if OPEN_DOCUMENT_TREE was implemented I could use it alternatively. This would probably also help some ATVs that have no Files app.

**Comment by sbr5136014** [comment]
Is there any update on OPEN_DOCUMENT_TREE ?
