### ISSUE TITLE
Add remount to read-write when operating on /system and /vendor

### ISSUE THREAD

**Issue by acroreiser** [zhanghai/MaterialFiles#128]
When user trying to operate in "root only mode"
with file on /system mount point, file manager fails to do action with error "read only file system".

![Screenshot_20190712-212437_Material_Files](https://user-images.githubusercontent.com/10716792/61150219-98d6e200-a4eb-11e9-8d41-a8bb06ee75f1.png)

**Comment by zhanghai** [comment]
References:
- https://stackoverflow.com/q/5467881
- https://github.com/Stericson/RootTools/blob/master/src/main/java/com/stericson/RootTools/internal/Remounter.java

**Comment by zhanghai** [comment]
More references:

- https://source.android.com/devices/bootloader/system-as-root
- https://android.googlesource.com/platform/external/toybox/+/refs/heads/master/toys/lsb/mount.c
- https://android.googlesource.com/platform/external/toybox/+/master/lib/portability.c
- https://android.googlesource.com/platform/system/core/+/master/adb/daemon/remount_service.cpp
- https://android.googlesource.com/platform/system/core/+/master/fs_mgr/fs_mgr_remount.cpp
- https://android.googlesource.com/platform/system/core/+/54ea49ba05a098a2e429ca27a4abae712928401c/adb/daemon/remount_service.cpp

**Comment by zhanghai** [comment]
Correctly remounting on Android turns out tricky because of things like system-as-root, dm-verity, bind mount, etc. We may remount `/system`, `/vendor`, but I'm not sure what happens to files under `/`. We need to choose to do our own implementation, or use toybox `mount`, but the latter isn't 100% correct either because the only correct implementation is the one used by `adb remount` on debug devices, while the former can be fragile to OEM modification. And remounting rw breaks systemless which Magisk is about. The user interaction is also tricky, because it might be better if we ask for confirmation before remounting rw, but that requires some amount of UI work.

I'm punting this to the next milestone.

**Comment by zhanghai** [comment]
Done. A remount r/w action is added to the dialog when ReadOnlyFileSystemException happens for linux path.

**Comment by acroreiser** [comment]
What about text editor? He told me "read only file system" when I tried to edit and save the file.

**Comment by zhanghai** [comment]
Oops... good catch. I'll try fix it in the next version. Meanwhile as a workaround, just do some file system modification in the same directory and trigger the dialog to set r/w before saving the file.

**Comment by zhanghai** [comment]
Closing this to track the bug in #163.
