### ISSUE TITLE
Root Timeout ignored

### ISSUE THREAD

**Issue by malcolm-dane** [zhanghai/MaterialFiles#1343]
Application ignores the root timeout by magisk unless force stopped. It will continue to have root permissions until stopped. if added to magisk deny root it will work.

**Comment by zhanghai** [comment]
I think that's intended behavior because this app needs to run a background service as root for potentially long running operations and for improving performance, so the Magisk timeout only gates the initial service start but won't kill the service after the timeout. You may try to force stop the app you've given root to in order to solve this if you care, but note that I think actually malicious apps will still have ways to work around that.
