### ISSUE TITLE
Trackers in the App

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [zhanghai/MaterialFiles#1347]
Hey,

i downloaded the Github APK for Material Files it showed me 2 Trackers. Here you can look them up: https://reports.exodus-privacy.eu.org/en/reports/470172/

I know that there is a Google Play Version and a F-Droid Version. And I checked in F-Droid if it shows installed and it didn't say that. So I'm guessing that the Github APK is the Google Play Version. Otherwise it would say installed in F-Droid but it just says recommended. 

So I wanted to ask if you could remove the two Trackers? I have a better Alternative for that, which is lightweight and even Open Source too. Look here: https://plausible.io/

Because I want to use your App but the Trackers hold me away from the App. I hope you can change that.

**Comment by zhanghai** [comment]
Yes, the F-Droid build is 100% FOSS and doesn't have Firebase/Crashlytics, which I use to see app version adoption and app crashes (and maybe halt release if I see a severe regression).

I understand different people have different levels of trust to big techs and/or their different products, but to me since I was merely collecting things like number of users and app version as well as crash reports, I'm personally fine with using a Google service that's readily available, easy to set up, free of charge and scrutinized by regulators - that unblocks me from focusing on more important aspects of the app. After all, there's the F-Droid version without it for people with a different opinion than me.

Plausible seems a paid service, so that is not going to work for me since this is just a side project of mine and I'm not getting paid by anyone (And I can't be, because that creates a conflict of interest with my day job), so I don't want to be paying for crash reporting either. I don't have the time to self-host and potentially deal with things like GPDR either.

I publish the GitHub APK when I cut a release and upload the new APK for that release. However, the F-Droid build process is out of my control (which helps safeguard your privacy even if you don't trust me), and that may take 1-3 days, so it's not something I can publish when I cut a new release.

So in this case I think you can just keep using the F-Droid version and getting the APK from F-Droid or any store that uses F-Droid as a source.

**Comment by PrivacyAndSecurity** [comment]
> Yes, the F-Droid build is 100% FOSS and doesn't have Firebase/Crashlytics, which I use to see app version adoption and app crashes (and maybe halt release if I see a severe regression).

I understand that but it is still in main F-Droid Repo which has Security Issues. And you could use for the App everything in non Google and Open Source Analytics from Plausible, which I mentioned before. It does the same Job, while degoogling, being leightweight and Open Source. 

> I understand different people have different levels of trust to big techs and/or their different products, but to me since I was merely collecting things like number of users and app version as well as crash reports, I'm personally fine with using a Google service that's readily available, easy to set up, free of charge and scrutinized by regulators - that unblocks me from focusing on more important aspects of the app. After all, there's the F-Droid version without it for people with a different opinion than me.

I understand that but it would be better then to publish the Foss App in Github, which is not a F-Droid Build, just a clean Build without F-Droid.

> Plausible seems a paid service, so that is not going to work for me since this is just a side project of mine and I'm not getting paid by anyone (And I can't be, because that creates a conflict of interest with my day job), so I don't want to be paying for crash reporting either. I don't have the time to self-host and potentially deal with things like GPDR either.

I understand that but see the 9$ per Month as investition for your App, the Community and to degoogling it. But there should be free Open Source Analytics probably too, if you research.

> I publish the GitHub APK when I cut a release and upload the new APK for that release. However, the F-Droid build process is out of my control (which helps safeguard your privacy even if you don't trust me), and that may take 1-3 days, so it's not something I can publish when I cut a new release.

I understand your point but why not clean FOSS Build APK in Github - without being a Google Play or F-Droid Build? That would be ideal for us as Users from the Community.

> So in this case I think you can just keep using the F-Droid version and getting the APK from F-Droid or any store that uses F-Droid as a source.

No, I don't trust the Main F-Droid Repo because of their Security Issues. Look here: https://privsec.dev/posts/android/f-droid-security-issues/

If you want to publish it, then do it in the IzzyOnDroid Repo, which has not these Security Issues and do always check the Apps for Malware and everything. Or launch it on your own F-Droid Repo or launch it only in Github, without being a F-Droid Build.

**Comment by zhanghai** [comment]
I still trust F-Droid even after reading the linked article because I don't consider the issues listed there as realistically impactful enough.

I'm also surprised that there are people who want to trust me more than F-Droid for a build to de-Google, because although I personally have zero incentive to hurt people's privacy, my day job is still at Google. So I'm still not convinced a third official build of this app is worth it for my time and the potential confusion for general users.

I respect other people's decision to Google or de-Google, but I don't have any plans to pay for a side project that I earn nothing from, and I don't have the time or want to self-host either.
