### ISSUE TITLE
Add amoled black toggle

### ISSUE THREAD

**Issue by MingoMGx** [zhanghai/MaterialFiles#157]
Add an amoled black toggle when dark mode is enabled. So users can match the dark theme with the dark theme of the device.

**Comment by keganlance** [comment]
Would love to have this as well. It's a must have to make the app look clean on such device and to save battery.

Just some toggle to make the black in the night mode pure black would do the trick

**Comment by zhanghai** [comment]
I'd like to have it as well, but the problem is that implementation-wise this isn't trivial.

Currently I'm implementing night mode in the official way, by overriding resources in `values-night` etc. But since there isn't a `values-night-amoled` thing, there can only be one night mode. I assume adding another AMOLED night mode can still somehow work in another way but it will be complex and make code much more ugly. It is also actually against the official Material Design guidelines which specified the colors for night mode to be [dark grey instead of black](https://material.io/design/color/dark-theme.html), which means that it is also unlikely to ever get official support. For the reasons above, I don't currently have a plan for AMOLED black.

That being said, you can still create your own build and replace the colors, or in a cleaner way, create a Substratum theme (or something similar) that utilizes RRO to replace color resource in this app during runtime.

**Comment by keganlance** [comment]
Understood. However, currently you already have two themes. The classic Material Design, and Google's Material Theme (which you call Material Design 2). Instead of implementing it as values-night, could it possibly be configured as a separate theme like the above?

**Comment by zhanghai** [comment]
Added in f5e27c6.

**Comment by naveenjohnsonv** [comment]
I  see you added amoled toggle but I can't find it anywhere in the settings in the latest Tennessee

**Comment by zhanghai** [comment]
It's added in the code base, but you will need to wait for the next app release.
