### ISSUE TITLE
Add large screen/tablet view support

### ISSUE THREAD

**Issue by berserkore** [zhanghai/MaterialFiles#177]
Great work! it would be great to add support for tablet & large horizontal screen by having:
- A sticky left menu/drawer for quick access of directories and options
- A right side preview when clicking on a file/medias

Here is a quick example of how it looks like:
![demo](https://user-images.githubusercontent.com/11094066/69123581-d4b33100-0af5-11ea-96dc-370808865ff6.png)

Hope you like the idea.
Have a great day

**Comment by zhanghai** [comment]
It is already implemented.
![tablet-10in.png](https://github.com/zhanghai/MaterialFiles/blob/master/screenshots/tablet-10in.png?raw=true)

**Comment by berserkore** [comment]
It's supported for tablets but here is what we get on a large screen Android TV:

<img width="1025" alt="Screen Shot 2019-11-19 at 21 04 37" src="https://user-images.githubusercontent.com/11094066/69137167-51eb9f80-0b10-11ea-800d-e3eef162ca5b.png">

**Comment by zhanghai** [comment]
It's not working for TV because tablets are differentiate by having a minimum width of 600 dp, and the TV device doesn't have that many dps.

Before I commit to supporting TV, does the app already plays well with remote control otherwise? I heard that developers should use the leanback library to build specialized layout for TV, instead of using the phone/tablet layout.
