### ISSUE TITLE
 add splahscreen

### ISSUE THREAD

**Issue by odrevet** [zhanghai/MaterialFiles#185]
When the app is run the screen flashes to white for a brief time. 

This is especially annoying when launching the app when in the dark. 

When the app is loading, the sceen could be the selected theme canvas color, optionally with a loading spinner.

**Comment by zhanghai** [comment]
I would love to, but the "screen flashes to white" is caused by system using the theme staticly declared in AndroidManifest.xml to create a temporary placeholder, which cannot be modified dynamically. Even if I add a splash screen, it will splash white for a brief time before the splash screen. Or if we change the theme declared in AndroidManifest to be the dark theme, it will flash black for white themes instead. So sadly this is just infeasible.
