### ISSUE TITLE
Input field issue when keyboard is up

### ISSUE THREAD

**Issue by ivadham** [zhanghai/MaterialFiles#210]
# Environment

```
Android version: LineageOS 16.0 based on Android 9.0
Screen resolution: 1080x1920
Material Files version: 1.0.1
```

# Steps to reproduce

Open an input field. New File, New Folder, Rename, Compress, you name it...

# Actual behavior

Only a part of input field can be displayed, and it is scrollable.

# Screenshots

![Screenshot_20191212-211549_Material_Files](https://user-images.githubusercontent.com/11696957/70736627-f9ca4680-1d25-11ea-9fda-6dfbe9a21d84.png)
![Screenshot_20191212-213003_Material_Files](https://user-images.githubusercontent.com/11696957/70736928-a9071d80-1d26-11ea-8ad4-bd3d00df7566.png)

**Comment by zhanghai** [comment]
Well this is awkward... simply put the screen is too small with the standard MD2 spacing. And I should not modify it because they are standard values in the Material Components for Android official library, and changing them impacts other users. The expected behavior on screens that are too small is, in fact, just scrolling...

Did you ever modify your DPI setting (in Settings > Display > Display size)? The UI elements in the screenshot looks bigger than expected. If so, reverting to the standars display size may help.

**Comment by afmbsr** [comment]
I have the same issue on (Huawei Y5 Prime 2018), even with the standard display size, except when I downgrade it to a smaller value

**Comment by ivadham** [comment]
My DPI setting (aka Display size) was Default. I switched to Small, and it fixed the issue. It took a day or two and now I'm used to Small DPI, yeay :)
