### ISSUE TITLE
Wrong capacity shown for external USB drive

### ISSUE THREAD

**Issue by neneko** [zhanghai/MaterialFiles#234]
Tried both with and without root access mode. It's a 256GB drive with about 45GB free space, formatted as fat32.

![Screenshot_20200209-114416_Material_Files](https://user-images.githubusercontent.com/59116948/74100900-fe4b8980-4b33-11ea-8624-0ef1e25a3aa2.png)

This is the correct size show in the default LineageOS file manager, com.android.documentsui:
![Screenshot_20200209-115557_Files](https://user-images.githubusercontent.com/59116948/74100903-060b2e00-4b34-11ea-93da-c55a2f905eec.png)

I'm on LineageOS 16 Android 9, with the latest build from F-droid, 1.0.1 (16).

**Comment by zhanghai** [comment]
It seems there actually isn't a good way for a regular app to determine the total space on a USB device.

The bug here is that the app took the space of the system partition if `File.getTotalSpace()` doesn't work, however this should not apply to a USB device. This bug will be fixed, and the size just won't show up there.

**Comment by zhanghai** [comment]
Fixed in 4b88da3.
