### ISSUE TITLE
cannot extract rar file

### ISSUE THREAD

**Issue by disdagithubacc** [zhanghai/MaterialFiles#247]
thanks for such a nice and clean app though.
i'd like to report this one issue: some rar files (e.g. this one: https://www.rarlab.com/themes/RARaddin_48x48.theme.rar) can be viewed without any problem but when i try to extract them, it just hangs. 
also app is not able to handle encrypted archive files(zip, rar...) 
tested on the latest 1.0.2 release.

**Comment by ssssamstrup** [comment]
Can't extract zip-files

**Comment by shavez2315** [comment]
Unable to extract rar files. Otherwise the app is fantastic.

**Comment by quite** [comment]
How is extract supposed to work? Some support app needed? 

When I try "Extract" on a Zip, a bar saying "Extracting 1" (plus a close button, and a clipboard icon) appears at the bottom. Tapping the icon gives a bubbler saying "... No archiver found ..."

**Comment by Nogooduser** [comment]
Any updates on this issue? It's been over a year now.

I can't extract any rar files myself. Not sure if they're different or what but every far file I've downloaded so far doesn't open with Material Files. 

I can extract them with other apps, so clearly the files themselves are fine and not corrupted. It's just Material Files that can't seem to extract them.

**Comment by zhanghai** [comment]
The RAR support in this app is directly backed by [junrar/junrar](https://github.com/junrar/junrar), so if an RAR archive can't be handled by this app it's likely an issue in that library.

Note that I'm not profiting from this app and it's only a side project of mine, so please don't feel unexpected if an issue isn't seeing action even after a year. If you consider the bug critical to you, please help investigate the root cause of bug to reduce the work I'll need to fix it.

I've got some time today to actually debug this and it's indeed an upstream issue for the issue in the first comment, where the file can be opened but everything extracted is empty. I've filed https://github.com/junrar/junrar/issues/83 for this. However if your issue is that you can't open any RAR file, you will have to provide a way for people to reproduce it before anyone can possibly take a look.

(Also note that RAR support is being dropped on F-Droid builds anyway due to clarification on F-Droid inclusion policy (#699).)

**Comment by zhanghai** [comment]
RAR 5 is now supported via libarchive (#735), and will be available in the next release. Note that encryption isn't supported by libarchive yet.
