### ISSUE TITLE
Add per-app language preference

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [zhanghai/MaterialFiles#293]
There is no function to change the app language without changing the Android system language.

### App Version

Material Files 1.1.1
https://github.com/zhanghai/MaterialFiles/releases/tag/v1.1.1

### Android Version

Android 9

**Comment by zhanghai** [comment]
This is tricky to implement. Why do you need a different locale inside the app?

**Comment by ndnddkoeo3dkej9** [comment]
I prefer some applications in English, which is not my system language. Material Files is an app that I use several times a day, sometimes even hours.

**Comment by zhanghai** [comment]
OK, I'll consider doing this.

**Comment by Hug385** [comment]
![IMG](https://user-images.githubusercontent.com/68834676/88499753-14a4af00-cfc7-11ea-81c5-aeb759dcff79.jpg)

I recommend to use the Files by Google App, because this app can do this and that without the app restarting.

**Comment by aisbergde** [comment]
there are many reasons to use apps in English:
* bad or suboptimal translations
* it is hard to describe issues or to ask support, if the GUI is translated

**Comment by zhanghai** [comment]
The current plan is to wait for the Jetpack port of the Android 13 API: https://developer.android.com/about/versions/13/features#app-languages

**Comment by aisbergde** [comment]
My smartphone has Android 11, maybe it will get Android 12, and I have no idea, if it will get Android 13.
But it looks like a possible solution to wait for Android 13, because the issue is not a blocking issue. The app is just a bit hard to use because of suboptimal translations.
It is a General issue of many apps and programs, that they try to provide translations, instead of just using English. English is not my native language, but software usage in English is much easier, then to try to understand strange translation, to try to translate back into English to understand the possible meaning. Whenever possible I try to disable translations. In some projects this is not possible. And then I need to use for example Visual Studio or SQL Server Management Studio in German. And even the professional translations are so hard to use. Sometimes I find what I need just because I know, where it is located in the English version.

Long writing, short content: What about disable translations at all until Android 13 and deliver the app only in English?

**Comment by zhanghai** [comment]
@aisbergde, I believe you might had a misunderstanding of my last comment. I was talking about **the Jetpack port** of the Android 13 API, which is supposed to work on most Android versions (e.g. Android 5.0+) instead of only Android 13+.

I don't think simply removing all translations will make the majority of users happy either, since there are also people who spend their time adding/improving the translations. If you see a translation issue, you can always go to [Transifex](https://www.transifex.com/zhanghai/MaterialFiles/dashboard/) and fix it.

**Comment by aisbergde** [comment]
Reading my own comment, I found an easy solution: I just changed the default system language to English. And now I can also use international solutions for other smartphone issues. I should do this also on my Windows system.
And you are right, most users prefer translations. So, you are on the right way!

**Comment by zhanghai** [comment]
This is blocked by AppCompat 1.6.0 stable release, so punting to v1.6.0.
