### ISSUE TITLE
Can not modify files in SD card

### ISSUE THREAD

**Issue by nhfo** [zhanghai/MaterialFiles#297]
This is observed on OnePlus X (Android 6.0.1). Device has micro SD card. App shows two storages by default, "Internal storage" and "SD card". 

All operations involving write to filesystem fail with app receiving AccessDeniedException (with root access mode at normal).

If a storage is added for SD card using "+ Add external storage", then operation do not for this storage. Operations in "SD card" storage still fail.

**Comment by zhanghai** [comment]
What is the app version you are using? I assume the most recent version won't show two storages by default.

**Comment by nhfo** [comment]
App version is 1.0.2, f-droid build.

**Comment by nhfo** [comment]
App version 1.1.1, both from f-droid and play store, also show two storages.

**Comment by zhanghai** [comment]
The thing that the app shows SD card by default is weird, because I'm checking [`StorageVolume.isPrimary()`](https://developer.android.com/reference/android/os/storage/StorageVolume#isPrimary()) to [only show the internal storage by default](https://github.com/zhanghai/MaterialFiles/blob/0ca732d2050844f41e6a2f18fcebccea7b559c9b/app/src/main/java/me/zhanghai/android/files/navigation/NavigationItems.kt#L67), and the SD card should actually only be available after being added by `Add external storage…`. I'm not sure why H2OS/OOS 6.0 would tell me there are two primary storage volumes, and I think it's an OEM bug because the doc clearly said:

> Returns true if the volume is the primary shared/external storage, which is the volume backed by Environment#getExternalStorageDirectory().

which means there shall only be one such storage at a time.

If SD card write works after being added by `Add external storage…`, that's the intended behavior, and you can just ignore the SD card reported by system as primary storage. I don't really want to have workarounds for OEM-specific bugs in code unless it's impacting core functionality, because they will be hacky and a burden to maintenance. My phone is an OnePlus 5 with OOS 9.0 and it doesn't have such an issue, so maybe you can also consider ugprading 😅
