### ISSUE TITLE
Alternative for SDK developer or library to embed this File Manager

### ISSUE THREAD

**Issue by mochadwi** [zhanghai/MaterialFiles#320]
Thanks for this great library. Is it possible to be added as dependency so I can embed the **MaterialFiles** whenever I want to pick/choose file in my apps, e.g: multiple selection and share the selected files, without users needs to download or install MaterialFiles

**Comment by mochadwi** [comment]
@zhanghai

**Comment by zhanghai** [comment]
> Thanks for this great library.

This is an app instead of a library. Making it a library requires a lot of other work, and even if so it will be bring a ~4MiB size increase which is undesirable for most apps, so I don't have plan for doing this. However, you can always bring up a file picker with `Intent.ACTION_GET_CONTENT` or `Intent.ACTION_OPEN_DOCUMENT`, and the user may choose to use the system file picker, or if they had this app installed, Material Files.
