### ISSUE TITLE
[Feature] File list pinch to resize text

### ISSUE THREAD

**Issue by SebiderSushi** [zhanghai/MaterialFiles#328]
On the regular display size of android, the file list does not fit many entries or long filenames.

The most awesome & intuitive solution (in my opinion) could be to implement a "pinch to zoom" gesture on the file list to control the entry/text size / amount of details displayed per entry. That way, the amount of entries versus text size could always be adapted to the current needs of the user.

**Comment by zhanghai** [comment]
I know some apps do this, but IMO it isn't ideal from a design perspective, because apps should have proper size and spacing for list items. Plus I have to write and maintain it while I personally will never use it :/ I do have plan to add grid view though, and maybe provide an option to marquee long text in list mode.

**Comment by SebiderSushi** [comment]
Okay, thank you very much for your answer!
