### ISSUE TITLE
Device connected via USB Type-C OTG is not shown

### ISSUE THREAD

**Issue by xxxxq64** [zhanghai/MaterialFiles#334]
Hi,

I have a Realme X50 Pro and a Xiaomi Mi 9, both have Android 10 and Material Files (1.1.2).

When I take a USB-C to USB-C cable and connect my 2 Android devices, nothing is displayed in Material Files.  It does not show the internal storage of the other Android device. X50 Pro is the host in this case.

When I use Android devices that also have an SD card, this storage is also not displayed.

**Comment by zhanghai** [comment]
Material Files only supports OTG if the system supports it. You can try `Add external storage` in the drawer and see if there is an entry in system file picker for the other device. If there is, selecting that entry should work, otherwise I don't have a plan to support OTG natively in this app, yet.

**Comment by xxxxq64** [comment]
Thanks with the tip with "Add external storage".  That worked.  :)



I can see the internal storage from the other Android device and also the SD card from the other Android device.

But there is a problem, when I copy files or folders the timestamp is not the same. Can you fix it?

**Comment by zhanghai** [comment]
No, because the Android system doesn't support setting modified time for files.

The Android system `DocumentsProvider` for external storage, which is [`ExternalStorageProvider`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/ExternalStorageProvider/src/com/android/externalstorage/ExternalStorageProvider.java), extending its base class [`FileSystemProvider`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/com/android/internal/content/FileSystemProvider.java), both don't contain any reference to `File.setLastModified()` in their implementation. They only allow querying the last modified time, but not setting it, so Material Files cannot update the last modified time to be the same as the source file after copying.

**Comment by xxxxq64** [comment]
I'm sorry. Now I have added more information about modified time.

https://github.com/zhanghai/MaterialFiles/issues/335
