### ISSUE TITLE
Make MaterialFiles resizable

### ISSUE THREAD

**Issue by alexanderadam** [zhanghai/MaterialFiles#340]
I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the application is always nearly squarish:

![Screenshot of MaterialFiles on Samsung DeX](https://user-images.githubusercontent.com/372620/88279382-40cce100-cce4-11ea-9009-daa4bdf27698.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.

**Comment by zhanghai** [comment]
> If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.

https://developer.android.com/guide/topics/ui/multi-window#resizeableActivity

This app targets API level 29 and isn't specifying this attribute, so it is Samsung's customization that seems to be deviating from the official documentation, and please report this bug to Samsung.

**Comment by alexanderadam** [comment]
So you think that my chances are higher that Samsung fixes something, than for an app where I directly can reach the maintainers?
Also apps like VLC or Firefox are flawlessly resizing and [GitNex also just got a fix for that](https://codeberg.org/gitnex/GitNex/pulls/601/files).

Would you please reconsider your decision? :pray:

**Comment by SebiderSushi** [comment]
Okay so Samsung is at fault here but what's the drawback of adding one line to explicitly declare a value to be the same as the supposed default?

**Comment by zhanghai** [comment]
If everyone starts doing this, Samsung can keep their inconsistent behavior forever and it becomes a de facto standard, succeeding in fragmenting the Android ecosystem, while every app doing so is helping to perpetuate the fragmentation. And if every OEM starts doing similar things for the smallest corners of Android, developers would end up in a fragmentation hell, become less motivated and maybe even abandon the platform, resulting in less and worse apps for users in the long run. But I can get that generally users don't care about technical details and just want to have a more usable app immediately. I assume that as they can't reach Samsung engineers, they are just pushing the app developers to do the quicker "fix" because there's no obvious "drawback", and a lot of apps are doing it now.

While being unsatisfied with Samsung's behavior deviation, I do understand that making users happy is still important and compromises can be made. So here's the compromise: If prominent Google apps (e.g. Chrome, Drive, Play, etc) are unnecessarily (targetting API 24+) adding this manifest attribute, I can do it as well. Could anyone help me verify this?

**Comment by alexanderadam** [comment]
> If prominent Google apps (e.g. Chrome, Drive, Play, etc) are unnecessarily (targetting API 24+) adding this manifest attribute, I can do it as well. Could anyone help me verify this?

Sure thing. Here is a check on Google Chrome, Google Play and MaterialFiles: https://youtu.be/d6Hnqb-qiWE

**Comment by zhanghai** [comment]
This is the AndroidManifest.xml for Play pulled from my Pixel (target SDK version is `29` in another file):

```xml
<application
    android:appComponentFactory="com.google.android.finsky.appcomponentfactory.PhoneskyAppComponentFactory"
    android:backupAgent="com.google.android.finsky.setup.VendingBackupAgent"
    android:extractNativeLibs="true"
    android:hardwareAccelerated="true"
    android:icon="@mipmap/ic_launcher_play_store"
    android:killAfterRestore="false"
    android:label="@string/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f130087"
    android:name="com.google.android.finsky.application.classic.ClassicProdApplication"
    android:requestLegacyExternalStorage="true"
    android:requiredForAllUsers="true"
    android:restoreAnyVersion="true"
    android:restoreNeedsApplication="true"
    android:restrictedAccountType="com.google"
    android:roundIcon="@mipmap/ic_round_launcher_play_store"
    android:supportsRtl="@bool/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f05001e"
    android:usesCleartextTraffic="true">
```

As you can see, no `android:resizeableActivity="true"`.

For Chrome:

```xml
<application
    android::allowAudioPlaybackCapture="false"
    android::allowBackup="true"
    android::backupAgent="org.chromium.chrome.browser.ChromeBackupAgent"
    android::extractNativeLibs="false"
    android::fullBackupOnly="false"
    android::icon="@drawable/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f080191"
    android::isSplitRequired="true"
    android::label="@string/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f130193"
    android::largeHeap="false"
    android::manageSpaceActivity="@string/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f130477"
    android::multiArch="true"
    android::name="org.chromium.chrome.browser.ChromeApplication"
    android::networkSecurityConfig="@xml/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f17001a"
    android::restoreAnyVersion="true"
    android::roundIcon="@drawable/0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f080192"
    android::supportsRtl="true"
    android::use32bitAbi="true"
    android::zygotePreloadName="org.chromium.content.app.ZygotePreload">
```

Still none.

Since your video showed that the two apps are actually being resizable, it seems to me that Samsung is just having an internal allowlist for Google (or other popular vendor) apps to be resizable without being bent to their repurposing of `android:resizableActivity`. If this is really the case, this would fall into the yet another thing that I hate about some OEM customizations - they have an allowlist for popular apps to keep them working with existing best practices (because they know users would blame them instead of these bigger developers), and then force all other developers to abide by their non-standard rules.

To be clear, I'm not against add Samsung specific things for Samsung specific features - if they proposed a separate element to be added, e.g. `<meta-data android:name="com.samsung.metadata.DEX_RESIZABLE android:value="true" />"`, I would have happily added that. But their re-purposing of `android:resizableActivity` is explicitly deviating from the official documentation so I don't like to add it or help perpetuating it in our ecosystem.

**Comment by zhanghai** [comment]
Actually after some communication on this issue, I think I can add this until they start respecting the default value, which ARC is already doing.
