### ISSUE TITLE
Showing NTFS drives on Android-x86 or PhoenixOS

### ISSUE THREAD

**Issue by hmtheboy154** [zhanghai/MaterialFiles#341]
Hello. Apology for my bad English but I hope you can add this feature to the app. I am using PhoenixOS, an Android-x86 based OS which have a custom script to mount NTFS drives
https://pastebin.com/0EmBXGPW
You can see that the script the drives are mounted as /storage/disk*numbers* .
There is an app called FX File Manager which recognize all the mounted partitions in storage. But since FX hasn't been updated for months and I really love MD app like Material Files, can you add this feature to your app too ? 🗡️ 

Also, root or not it's ok since Android-x86 already have it

**Comment by zhanghai** [comment]
You can try to add a bookmark folder for each of the Windows partitions and they will be easily accessible.

This app is reading the storage volumes from Android framework's `StorageManager`, and I don't want to hard code custom paths to look for other storage. Inspecting the `mountinfo` also won't work because there might be a lot of mounts that doesn't make sense to a normal user but is useful to the system, and I don't see a way to differentiate between the two in `mountinfo`.

**Comment by hmtheboy154** [comment]
Is there anyway we can automate the bookmarking ? Like using `monkey` command ? 
Or where can I edit the file that contain bookmarks ? (maybe I can edit that file with a script)

**Comment by zhanghai** [comment]
I believe `monkey` is a monkey and it can only do random things with an app, but not performing a specific series of actions. You can write [Ui Automator](https://developer.android.com/training/testing/ui-automator) code if you really want to automate it, but adding a bookmark is really an one-off action so I personally wouldn't bother writing code for it. The file persisting the bookmarks are storing base64 encoded binary data structures for bookmarks, so you can only go this way if you are willing to read the code of this app and maintain compatiblity with whatever changes made to it.

I still recommend just manually adding bookmarks for the partitions that you care while using.

**Comment by hmtheboy154** [comment]
So I guess I'll have to manually bookmark then. 
Thanks for your help, it's very informative.
