### ISSUE TITLE
[Bug] Error while deleting

### ISSUE THREAD

**Issue by varbhat** [zhanghai/MaterialFiles#363]
When i try to delete "Android" folder, i get the "Error while deleting" popup. if i skip deleting, then retry to delete the folder again,folder gets deleted. I suppose that it is bug.

![errorwhiledeleting](https://user-images.githubusercontent.com/68165364/91146596-bc9bbe00-e6d4-11ea-80bd-9a8d47229db5.jpg)

**Comment by zhanghai** [comment]
One really shouldn't delete the `Android` folder, because it's a system directory where apps store their data.

I suspect this is because some app created a new file somewhere in that folder while the deletion operation is running, thus when this app thought the folder content had been cleared and tried to remove the folder itself, it actually contained that new file and couldn't be deleted. That being said, the second try might run significantly faster because most files under that folder has been deleted, leaving the offending app no time to create new files, and thus it succeeded.

If you reproduced this issue with an arbitrary folder instead of `Android`, please let me know and I can take another look.
