### ISSUE TITLE
Add "Paste path" or "Go to path" feature

### ISSUE THREAD

**Issue by PrSunflower** [zhanghai/MaterialFiles#367]
Hi, thank you very much for this app. I love the appearance and the animations, great work on the design! 👌

"Copy path" in the menu is very useful, but it would be awesome to have a "Paste path" or "Go to path" feature. This way the user could go to a complete path rather than having to browse each directory visually.

**Comment by jlxawk** [comment]
+1 for this feature, would be convenient if implemented in Meterial Files.

My scenario is accessing current user's directory tree of emulated storage, e.g. `/storage/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/0/`, such XXXXX is manually mounted from adaptive storage via `adb shell sm mount emulated:x,y` after each boot.

I think such kind of manual `adb` requirement is a misconfiguration (say, bug) of MIUI 11 (BTW it's a stock Redmi, I have no experience with other vendor's Android 11 ROM), this directory is also not listed in SAF.

Since its parent directory is not accessible by users, to view this directory tree, manually pass the path is required.  My current workaround is let Termux invoke `am start -n me.zhanghai.android.files/.filelist.FileListActivity -d file://<PATH>` to view PATH.

**Comment by zhanghai** [comment]
Done in #587.

**Comment by PrSunflower** [comment]
I saw the update, I now have a "Go to" option in the menu which works like a charm 😋 

Thanks @zhanghai ! Have a nice day.
