### ISSUE TITLE
[Feature Request] A lot of requests

### ISSUE THREAD

**Issue by RickyM7** [zhanghai/MaterialFiles#376]
I have several suggestions for improvements to the app, or rather, most of these things I've seen in other apps, but I believe that if these things are added to the app, the Material Files will just be amazing.

**1. Show icons from .apk and .pdf files**
Example:
![Exemplo de ícone](https://user-images.githubusercontent.com/24703825/95644662-7afd8180-0a8e-11eb-8ad9-dc3d0a545327.jpg)

**2. Show date and time of last modification and number of files in the folder below the folder**
Example:
![Exemplo de pastas](https://user-images.githubusercontent.com/24703825/95644761-1ee72d00-0a8f-11eb-9d7d-3e01a83c0bc6.jpg)

**3. APP text size**
This would give you an option to change the text size of the APP, regardless of your phone settings.This would be in interface settings and the text size would be regulated by a slide-bar with the percentage of the text size and an example of text below the bar showing how it will look.

**4. Prefer to open files in the APP**
This would make the app only open files in other apps when the user clicks "Open with", and would cause the window with apps recommendations to open the file to be shown only when clicking "Open with".

**5. Built-in audio and video player**
The app would have its own audio and video player. It would be a simple player, with basic options, like pause and fast forward.

**6. Modify and view files on the SD card (external storage)**
It would cause any file (be it .zip, .txt, .apk, etc) to be viewed, edited, extracted and etc, directly in the external memory. This seeks to solve some problems, for example, currently the app does not support extracting or viewing .zip files if it is in external memory.

**Comment by zhanghai** [comment]
1. APK icons are shown on internal SD card, PDF previews aren't (requires bundling extra library). Loading APK icons generally requires raw file access, which isn't avaialble on external SD card.

2. It's already raised elsewhere.

3. No, I won't provide and maintain options for everything (especially design-related) in this app, because my development time is limited and the app is following the Material Design guidelines. If you really want different text size/color/etc you can patch, compile and maintain a personal fork of the app yourself.

4. This is not how we open files in Android. Some other users may prefer their own external choices over the internal one, and this would ruin the experience for them, so I'd rather stay on the standard practice.

5. Well, I do hope so as well and maybe I'd write them some day, but (high-quality) code doesn't just pop up from nowhere. For now there are other priorites for this app and one may just stick with their own player app.

6. Text files are indeed viewed/edited directly. ZIP file requires raw file access which isn't really available on external SD card (similar to 1, a system restriction), so I can't do much here.

**Comment by RickyM7** [comment]
@zhanghai Thanks for the answers.
