### ISSUE TITLE
The privacy policy is completely inacceptable

### ISSUE THREAD

**Issue by KOLANICH** [zhanghai/MaterialFiles#386]
It is inacceptable to collect info from users' devices. It is also inacceptable to use third-party tracking libs.

**Comment by zhanghai** [comment]
Please check out the F-Droid version with no analytics/crash reporting, the link is in README.

I myself as a developer do need some data to tell me how my app is doing and what bugs are happening in the wild, so that I may improve the app. I don't want to go to great lengths to set up some kind of custom analytics (it's off my focus and fun) so I'm just using what the majority seems to be using. This is just one of my side projects and I'm not profitting from it anyway.

**Comment by KOLANICH** [comment]
Could a few words be added into PRIVACY.md (maybe close to the document top) indicating that F-Droid version collects no data and that the following policy is applied only to other versions?

**Comment by zhanghai** [comment]
I cannot provide direct info for how to install APKs (outside Play store) in my app published on Play store, because that will be a Play policy violation and I'll risk my developer account.

**Comment by rancidfrog** [comment]
Which version is on github release section?

**Comment by zhanghai** [comment]
The Play version built and signed by me. I upload both the APK I built with my signature as well as the ProGuard obfuscation mapping. The F-Droid version isn't built by me, but by F-Droid's own server with their signature, and typically have a delay of 1-3 days due to the way they operate the build process, so it isn't uploaded to the GitHub release.

**Comment by rancidfrog** [comment]
Thank you for the response.
I usually prefer github releases by developers rather than 3rd party fdroid which has delay problems on releasing new versions.

**Comment by KOLANICH** [comment]
>I cannot provide direct info for how to install APKs (outside Play store)

Can then `PRIVACY.md` be renamed? It may be possible to create a dir `privacy_policy` with 2 files `no-tracking.md`, and `with-tracking.md` and a bunch of symlinks (git supports symlinks, but sometimes it is disabled by default, can be configured in `.git/config`) to the right file named after the stores to which they apply (`GPlay.md -> ./with-tracking.md` and `F-Droid.md -> ./no-tracking.md`).

**Comment by zhanghai** [comment]
I  think an easier approach would be simply removing the "Privacy" item in the about page for F-Droid version - the F-Droid version doesn't upload any data anyway.

**Comment by KOLANICH** [comment]
>removing the "Privacy" item in the about page for F-Droid version

won't lift the confusion when visiting the repo. Having `PRIVACY.md` in the root of the repo makes impression like if it applies even to self-built apks.

**Comment by zhanghai** [comment]
If you do build the app directly from this repo without the transformations in F-Droid build script (some `sed` magic), you will get the analytics, so having a PRIVACY.md is still working fine.

**Comment by KOLANICH** [comment]
>If you do build the app directly from this repo without the transformations in F-Droid build script (some sed magic), you will get the analytics, so having a PRIVACY.md is still working fine.

Can it be reversed? I mean, making it have no "analytics" by default, and analytics is added only when it is explicitly requested to be added?

**Comment by zhanghai** [comment]
I've hidden the privacy policy on F-Droid build in cc14df9.

I don't want to reverse that state because my own focus is still on the Play build, so it should be the default state of the repo.
