### ISSUE TITLE
When I open a zip file from anywhere in my android then MaterialFiles should a an option to open it with!

### ISSUE THREAD

**Issue by prateekmedia** [zhanghai/MaterialFiles#405]
I cannot open a zip file with this app from other apps  as this app is not shown as an option to open from.

I am talking about "Open with" prompt to be clear.

Expected behaviour : Files should be an option to open zip files

**Comment by zhanghai** [comment]
Because this app cannot open ZIP files from them. Modern Android doesn't allow passing actual file paths, but the ZIP library this app is using requires an actual file.

This app never intended to be a fully feature archiver app, so please download a dedicated archiver app for these use cases instead.
