### ISSUE TITLE
FTP Server BUG ! All SD card corruption ! 

### ISSUE THREAD

**Issue by oopen** [zhanghai/MaterialFiles#428]
Start FTP Server, have corrupt all files on my SD card !

Steps to reproduce :

- start server
- stop server
- cry !

All files on target dir are corrupted !
Size is 0 octet.

**Comment by zhanghai** [comment]
What is the app version, Android version and device model you are using?

**Comment by oopen** [comment]
Armor_3W
Last stock rom : GQ3060RF2_AGS62_Ulefone_EEA_20200903_V09（Eu）
Android 9
Last available on f-droid : v1.1.4
I have verified the bug 3 times.
Eatch time all files in target dir, si lost (size set to 0 octets)

**Comment by zhanghai** [comment]
This is likely an OEM (Ulefone? The first time I've heard of it) bug because I (and other users) never encountered it. I don't have such a device to debug it so I can't fix it either, and I don't think I have any intentionally bizzare code that may set files to 0 bytes. So you should probably just use some other FTP server app and never use the one in this app :/
