### ISSUE TITLE
Submit to LineageOS

### ISSUE THREAD

**Issue by Donkey-Doug** [zhanghai/MaterialFiles#449]
LineageOS uses the default AOSP file manager. Perhaps you could suggest for material files to be the standard app?

**Comment by zhanghai** [comment]
If they are using the default AOSP file manager (DocumentsUI) I think it's fine for most users, and it should stay there because it contains some system functionalities besides being a file manager.

Back in the days of CyanogenMod, they had a CMFileManager alongside DocumentsUI and it worked fine (except some bug with root). So this CMFileManager app would be the ideal target for replacement. I found [LineageOS/android_packages_apps_CMFileManager](https://github.com/LineageOS/android_packages_apps_CMFileManager), but the latest commit there was in 2017, so I'm not sure if they ship it with current LineageOS builds at all.

I've been busy with my day job recently, so I don't have the time to get this app into LineageOS on my own. But if you open a discussion with LineageOS developers and add me, I'll be happy to answer their questions.
