### ISSUE TITLE
Cannot open Android/data Folder on MIUI12

### ISSUE THREAD

**Issue by RuofengX** [zhanghai/MaterialFiles#466]
MIUI Version 12.5
Material Files Version1.2.0
Root access NO
Cannot open Android/data Folder, screen shows that root access is needed. How it happens? And I notice that next version(1.2.1) will add support to Android11, is that about to fix this issue?
Thx for providing such awesome app!
[crashScreenShot](https://user-images.githubusercontent.com/40327863/111274847-7312c080-8670-11eb-917e-eb37a1f50d87.jpg)

**Comment by zhanghai** [comment]
> How it happens?

https://developer.android.com/about/versions/11/privacy/storage

So you can't access this directory by regular means. If you have root, you can access it with root. And in v1.2.0, you can access it by clicking Add storage -> External storage and then select either internal storage root or the Android folder. 

> And I notice that next version(1.2.1) will add support to Android11, is that about to fix this issue?

No, the restrictions will only get stricter with target SDK and Android system version rising.

The workaround by adding external storage will likely be fixed by Android once this apl targets Android 11+ and runs on Android 12+.

**Comment by RuofengX** [comment]
That's works for me, thanks!
