### ISSUE TITLE
[Samba] unable to connect to samba path

### ISSUE THREAD

**Issue by Generator** [zhanghai/MaterialFiles#470]
## Description
Samba client doesn't allow to add path for server (ex: smb://sambaserver/path )

## How to resolve
Add an additional field for samba path

**Comment by zhanghai** [comment]
Can you just connect to the server first?

**Comment by Generator** [comment]
I can only using IP or hostname, with path (sambaserver/path) returns error on connect

**Comment by zhanghai** [comment]
Yes, I know. Can you just connect to the server first?

**Comment by Generator** [comment]
Yes, only without path.
When using ``browseable = no`` on smb.conf there's no way to connect with specifying path

**Comment by zhanghai** [comment]
I see. Yes, currently this app requires the SMB server to be browseable, which Windows SMB servers do by default. I originally considered connecting directly to a share, but didn't actually implement it because of the additional code complexity to handle two types of SMB server roots, one being the list of shares and the other being files under root directory of a share. I can consider this as a feature request (to support connecting to a share directly), but I can't promise when it will land. As a workaround, you can keep the `browseable = yes` for now.

**Comment by Generator** [comment]
For future reference, proper workaround:
**smb.conf**
```
[share]
...
browseable = no
...
include = /etc/samba/%U.conf
```
Create ``/etc/samba/<user>.conf`` (replace <user> with username), add line ``browseable = yes``.
 This way hidden shares will stay hidden, only browseable for selected users.

**Comment by BerziOnline** [comment]
I would really appreciate the function of using a path. In Germany many users have routers from AVM (FritzBox) where you're forced to give a path to access the samba share.

**Comment by zhanghai** [comment]
Actually there might be another way to provide a initial path - let me experiment it later and this may be implemented in the next version.
