### ISSUE TITLE
💡 Idea: Ability to move files without using Cut and Paste (which changes the creation date of files).

### ISSUE THREAD

**Issue by ssssamstrup** [zhanghai/MaterialFiles#500]
I recently sorted a lot of files on my phone, including my images using this app, and it completely fucked my archive up.

Since there's no »move« command in the app to move files I used »cut« and »paste«. Using cut and paste changed the creation date (metadata) of the files, from the original creating date to the time of moving/pasting. Which in turn scrambled my whole image archive. I had to manually fix it by copying the exposure date (which contained the original creation date and time) to fix it again, which took hours. :(

I didn't think about it when moving/pasting the files, since most other apps don't do this.

I've now found I can move images files with my gallery app and another filemanager for moving other files, but I'd like to be able to keep using Material Files, so these workarounds pains me.

I don't know why the cut and paste does this (I guess it deletes the file and then creates a new copy?) and I'd love for you to consider changing this so the original »creation date« is kept in metadata and only the »file modified« date is updated.

Or add a »move« option that does this. I'd be afraid most other people will think Cut and paste does this too though (like I did unknowningly), so maybe it could best to change the »cut and paste« to »move« (?).

I use Android 11 on a Sony Xperia XZ2 Compact

(btw - glad to see the Hall of shame page - I'll go report them now! 🙌)

**Comment by zhanghai** [comment]
Cut and paste is actually supposed to be move, and move is supposed to preserve all file times if possible (while copy preserves only last modified time).

However, what do you mean by creation time? Because on Linux, there are only 3 standard file times, atime, ctime and mtime. atime is access time, which is the time the file is last accessed; ctime is changed time, which is the time the inode metadata (instead of content) of the file last changed, e.g. linux file permissions changed; mtime is the last modified time of the file, which is far more widely used than the other two. The actual file creation time is called crtime or birth time, but it's not that standard and not all file systems support it.

I have tested on my own phone that moving/copying files within internal storage indeed preserves the last modified time. This is also supposed to work on other filesystems, e.g. root/external storage (SD card)/SMB etc, but I don't have the latter two so although I have the code in place I'm not 100% percent sure that it will be preserved as well.

**Comment by ssssamstrup** [comment]
Cool! Then there must be an error happening somewhere.

I moved the files from phone to SD, so maybe the error could lie there?

I don't know about the linux metdata formats. I fixed the files on my mac where I in Finder can see three types of dates. I used an exiftool script with Hazel to fix them.

I'm not by my computer right now, but will update with the names of timeformats in Finder and the exifscript. Hopefully you can then figure out where the error happens.

If you need me to do some tests later with moving and checking files, I'll be happy to help with that. :)

**Comment by zhanghai** [comment]
See https://github.com/zhanghai/MaterialFiles/issues/335#issuecomment-661609094
