### ISSUE TITLE
Can't access Android/data in Android 11 MIUI 12 and i can't add Android/data as External Storage

### ISSUE THREAD

**Issue by fossfann** [zhanghai/MaterialFiles#515]
Hi all,

Hope you are doing fine. I have MIUI 12, stock ROM, not rooted, Android 11

I know we can access Android/data folder now by adding Android/data folder as an External Storage "but" when i pressed Add Storage -> External storage i am getting "No application found to handle this action" error. Is there any idea about this?

Any help would be appreciated!

Thanks in advance.

**Comment by zhanghai** [comment]
MIUI is known be have modifications and in this case it seems MIUI is missing the `DocumentsUI` system app. I believe having an app that handles the "Add external storage` action used in this app is part of the Android CDD so this is kind of strange - maybe your are using the China version instead of the International version of MIUI? The International version of MIUI should have to be CDD-compliant and should be able to handle this action.

But anyway, since this is a defect in the system, there's not much I can do in the app :/

**Comment by fossfann** [comment]
Thanks for the reply. I am using Global Stable 12.1.3.0 ROM not China or modded.

I checked now from Apps section i have com.google.android.overlay.modules.documentsui

If you can help i would be really appreciated!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zhanghai** [comment]
That's weird, I don't think this is expected on a compliant Android. `com.google.android.overlay.modules.documentsui` is an overlay package for theming and it doesn't provide the actual functionality. Could you check if you have `com.google.android.documentsui` or `com.android.documentsui`, or anything else named `documentsui`?

**Comment by fossfann** [comment]
> That's weird, I don't think this is expected on a compliant Android. `com.google.android.overlay.modules.documentsui` is an overlay package for theming and it doesn't provide the actual functionality. Could you check if you have `com.google.android.documentsui` or `com.android.documentsui`, or anything else named `documentsui`?

I checked now com.google.android.documentsui or com.android.documents.ui doesn't exist. I didn't uninstall those. Any idea?

**Comment by fossfann** [comment]
@zhanghai I installed com.google.android.documentsui by pm install-existing com.google.android.documentsui command and it worked!

**Comment by zhanghai** [comment]
Cool - maybe you somehow disabled it previously.
