### ISSUE TITLE
Preset SMB storage as default folder 

### ISSUE THREAD

**Issue by m-pastuszek** [zhanghai/MaterialFiles#533]
Hello,

Firstly, big thanks for developing this application! It's the best.

I'm preparing app preset to install it without need to setting it on each device due to commercial use. I'm close to have it done, but I can't set the default folder.

I use the SMB storage. How to add it's path to the `FILE_LIST_DEFAULT_DIRECTORY`? Using app settings, it works. I don't know how the path should look like... I've tried to do this many ways, but it's just not working. Maybe it should be done another way...

I mean this variable in `Settings.kt`:
```kotlin
val FILE_LIST_DEFAULT_DIRECTORY: SettingLiveData<Path> =
     ParcelValueSettingLiveData(
         R.string.pref_key_file_list_default_directory,
         @Suppress("DEPRECATION")
         Paths.get(Environment.getExternalStorageDirectory().absolutePath)
     )
```

**Comment by zhanghai** [comment]
Hi,

It surprised me a little bit this app is going to be distributed in a commercial context because it's just a side project of mine, but GPLv3 permits this so I won't be stopping you. Please keep in mind that:

1. As stated in GPL, this project is provided as-is and without any warranty, so it's your choice to use it in a commercial context and I won't be responsible for anything that happens from this, including and not limited to customer data loss or even device exploding.

2. If you are distributing a modified version of this app, you need to open-source your forked source code to comply with GPL. So if you plan to hard code some SMB credential in code that will also need to be open-sourced.

That being said, we can get back to the technical issue. You don't need to touch the default directories, but should add a new SmbServer item to the STORAGES instead.

**Comment by m-pastuszek** [comment]
Hi,

I want to explain this commercial use. We don't redistribute Your application and we will don't make any money on it. We only want to use it in our company due to production plans which are on SMB share. Your application is very great - material design and clear look makes job. Previously we used ES app, which had many ads and people were complaying about it. 

It will be much easier to deploy to all devices as preconfigurated.

Getting back to question, I already added the SmbServer, it shows up in menu and it is accessible, but defualt folder is still set as local device storage.

**Comment by zhanghai** [comment]
Oh sorry I misread your request as adding a standard directory. Yes, the default directory needs to be set to a path and that can be created with the SMB authority.

And yes, non-public distribution should be good without open sourcing your modification. Thanks for the explanation and glad you liked my app!
