### ISSUE TITLE
Passphrase for SSH keys when connecting to a SFTP server

### ISSUE THREAD

**Issue by takase1121** [zhanghai/MaterialFiles#552]
putting a ed25519 private key in sftp server option wouldn't work (invalid key format). sshj seems to support it, so are there any other showstopper for this to be enabled?

**Comment by zhanghai** [comment]
If it's invalid key format, maybe you are using an invalid format for the private key?

The key validation is at:

https://github.com/zhanghai/MaterialFiles/blob/06c396cd77f5823bd651c31d29ae2fb6a833e84c/app/src/main/java/me/zhanghai/android/files/provider/sftp/client/Authentication.kt#L46-L67

And a sample ECDSA key from SSHJ is at https://github.com/hierynomus/sshj/blob/master/src/test/resources/keyformats/ecdsa_opensshv1. I'm not sure about Ed25519 though.

**Comment by linsui** [comment]
Ed25519 works well for me.

**Comment by takase1121** [comment]
That's very odd.

I did some research, apparently OpenSSH has their own format compared to PEM, but that issue is supposed to be fixed in 2019. The only thing I can think of is that my Android version somehow don't support Ed25519, but that's also outrageous (I'm using android 10)

**Comment by bungabunga** [comment]
Today I had the similar experience, trying to use first Ed25519 and then RSA privat key, both with the "invalid private key" output. I made both keys with OpenSSH on Ubuntu machine.

**Comment by Slavko-P** [comment]
It also claims that keys generated by ssh-keygen (OpenSSH) on Termux as "invalid private key".  Even thought I use the key to access my SSH server via Termux.

**Comment by samyak-jain** [comment]
I'm getting invalid private key as well. And this is no matter which algo I use. I tried ecdsa as well as ed25519.

**Comment by DeeUnderscore** [comment]
Material Files reports "Invalid private key" if I try to add an encrypted ed25519 key (ie one with a passphrase). Without a passphrase it seems to accept the key and add the SFTP server entry (though I haven't tested if it actually connects). 

I guess the issue people are having here is not whether or not Material Files accepts ed25519 keys, but whether it accepts encrypted keys.

**Comment by samyak-jain** [comment]
So, my understanding is that sshj should support encrypted keys. I think if we just provide the passphrase here: https://github.com/zhanghai/MaterialFiles/blob/06c396cd77f5823bd651c31d29ae2fb6a833e84c/app/src/main/java/me/zhanghai/android/files/provider/sftp/client/Authentication.kt#L63, we should be good to go. Unless I'm mistaken, this is what we want: https://github.com/hierynomus/sshj/blob/8a66dc5336fc641b6fe7a607241f3dd7d36af5ad/src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java#L318

**Comment by zhanghai** [comment]
You can just provide a decrypted key - I don't see any benefit in introducing a new password field on the UI when the user selects public key authentication, which would further confuse some other users. Solid Explorer doesn't seem to allow providing an encrypted key and a password either.

**Comment by zhanghai** [comment]
I'm also updating SSHJ to 0.32.0 which claims to be addressing some key format issues, so maybe it will be helpful as well? (in the next version of this app)

**Comment by takase1121** [comment]
> You can just provide a decrypted key - I don't see any benefit in introducing a new password field on the UI when the user selects public key authentication, which would further confuse some other users. Solid Explorer doesn't seem to allow providing an encrypted key and a password either.

That's unreasonable. People who uses a passphrase on their key **expects** the program to prompt for their passphrase. **Not giving the prompt is confusing people more.** For example, I don't even know what you mean by "decrypted key".

**Comment by mrghosti3** [comment]
By decrypted key, I think he meant you can generate ssh keys without inputing any password while generating. This in term creates ssh keys that do not require pasword input before usage.

**Comment by takase1121** [comment]
> By decrypted key, I think he meant you can generate ssh keys without inputing any password while generating. This in term creates ssh keys that do not require pasword input before usage.

Why would I do that? I might as well as disable authentication if I just put up my key, unencrypted somewhere in the filesystem. Not to mention I'll have to swap all my keys out.

**Comment by mrghosti3** [comment]
Well there are certain situations where the private key without password might better option than one with it. Besides, if the permissions are setup correctly on the filesystem, no one else beside you should have access to it other than you. And you can perfectly setup the different private keys (lets say 1 with password, the other without) to able to connect on the same remote machine.

**Comment by takase1121** [comment]
> Well there are certain situations where the private key without password might be better option than one with it. Besides, if the permissions are setup correctly on the filesystem, no one else beside you should have access to it other than you. And you can perfectly setup the different private keys (lets say 1 with password, the other without) to able to connect on the same remote machine.

_Its a phone..._

**Comment by mrghosti3** [comment]
So? The way SSH keys work should still be the same. You are connecting from computer to phone? The you can have 2+ SSH available for usage on pc, but just use preferred one on the phone.

If it is from phone to other device. There is no issue to use private SSH key without password.

**Comment by takase1121** [comment]
> So? The way SSH keys work should still be the same. You are connecting from computer to phone? The you can have 2+ SSH available for usage on pc, but just use preferred one on the phone.

If it is from phone to other device. There is no issue to use private SSH key without password.

Okay, okay.... I'll just go and regenerate some keys and add them all to the server, create permissions out of _thin air_ on a FAT32 partition and connect to the server, voila!

Or I can put  a passphrase.

The thing is, I don't mind if this feature will take time. I just don't get why such a basic feature isn't supported and probably won't be supported based on author's response, especially their reason of "UI confusion".

**Comment by zhanghai** [comment]
Any other file manager that supports a password for the private key? I checked Solid and it doesn't seem to support this.

**Comment by Slavko-P** [comment]
> Any other file manager that supports a password for the private key? I checked Solid and it doesn't seem to support this.

https://github.com/x0b/rcx
https://sourceforge.net/p/gc-sftp/svn/HEAD/tree/src/main/java/com/ghostsq/commander/

**Comment by Kitt3120** [comment]
Same problem here, generated an ed25519 key with ssh-keygen on my arch machine. It's encrypted with a passphrase and the app does not recognize it as a valid format.

To confuse users less, how about a third option in the drop down, so you have Password, Public Key and Encrypted Public Key? Or if you select Public Key, there is a checkbox with the label "Encrypted" and upon activating it, the password field appears. A simple approach would be a permanent password field that has (Optional) in the label.

**Comment by Hajt5** [comment]
I'm getting error "invalid private key" no matter if I use rsa, dsa or ed25519...

**Comment by FBachofner** [comment]
> Any other file manager that supports a password for the private key? I checked Solid and it doesn't seem to support this.

Yes, MiXplorer by Hootan Parsa offers this functionality.

Because of this, I still use it instead of Material Files.

**Comment by zhanghai** [comment]
I plan to release a new version (v1.4.0) this weekend to address some other issues, and the current plan is to implement this in the version after that (v1.5.0).

**Comment by FBachofner** [comment]
Hello @zhanghai

>the current plan is to implement this in the version after that (v1.5.0)

This is exceptionally good news!  Thanks.

I see that you have regressions blocking 1.4.0  Good luck with that.  I wish I had the Android programming experience to help.

**Comment by VA1DER** [comment]
> That's unreasonable. People who uses a passphrase on their key **expects** the program to prompt for their passphrase

Please be careful about what you call unreasonable and how loudly you toss around words like "expect" with respect to an open sources volunteer software.

I don't think It's unreasonable to expect someone to trust their device with a private key.  If your threat model doesn't trust your device and you need an encrypted private key, the added security given by the pass phrase is mostly mommy medicine.  It may make YOU feel better but it isn't adding much (or really any) more actual security to the system.

**Comment by takase1121** [comment]
> > That's unreasonable. People who uses a passphrase on their key **expects** the program to prompt for their passphrase
> 
> Please be careful about what you call unreasonable and how loudly you toss around words like "expect" with respect to an open sources volunteer software.
> 
> I don't think It's unreasonable to expect someone to trust their device with a private key. If your threat model doesn't trust your device and you need an encrypted private key, the added security given by the pass phrase is mostly mommy medicine. It may make YOU feel better but it isn't adding much (or really any) more actual security to the system.

Please be careful about reading my comments, becsuse while I say that not being able to use a protected key is unreasonable, I **did not say that using a unprotected key is unreasonable**. What I find unreasonable is the author's excuse of "may confuse people" and "XXX doesn't have it". People are told to use (or at least know) passphrase when creating a ssh key. There is no reason why anyone would be confused about that. For the 2nd excuse, allowing user to input passphrase is supported in most ssh clients (including sshj I believe), so why wouldn't it not be supported? It's not like providing a passphrase is some sort of ancient deprecated practice or anything.

For my rude remarks to @zhanghai , I apologize. I've already reflected on it and will make sure to conduct myself politely in the future. 

I understand that this project is developed voluntarily, but what's wrong with having _an expectation of something?_ Am I not supposed to have an expectation for a feature because "hurr durr this is FOSS you should already be thankful that this exists"? I'm just trying to argue why this feature should be implemented, and here we are. Please, do not blow this out of porportion.

**Comment by VA1DER** [comment]
> Am I not supposed to have an expectation for a feature because <rude parody deleted>

That is exactly correct.  You should be thankful that @zhanhai is donating his time and talents.  You can hope for, ask for, and (better yet), contribute towards added features.  But you have zero _**expectation**_ of any feature or functionality.  Let me be rightfully clear.  You are not entitled to any expectation with respect to this software.  It doesn't matter how much you personally want a particular feature.  One of the first things you are presented with in the license agreement for this software:

>This program is distributed in the hope that it will be useful,
>but **WITHOUT ANY WARRANTY**; without even the implied warranty of
>**MERCHANTABILITY** or **FITNESS FOR A PARTICULAR PURPOSE**.

Read that carefully and understand it.  There are no promises made that this software will do what you want it to do.  There are no promises made that any particular feature will be implemented.  

> For my rude remarks to @zhanghai , I apologize ...

... and then proceed to rudely dictate the different things you find unreasonable in his software and response and label his responses as excuses.

> What I find unreasonable is

Irrelevant.  Not even going to address your ongoing rudeness.

Regarding the feature you are asking for...

> People are told to use (or at least know) passphrase when creating a ssh key. There is no reason why anyone would be confused about that.

Security doesn't exist in a vacuum.  Pass phrases are not just implemented for the sake of having a pass phrase.  In the wild 99% of ssh keys are used without passphrases because the inherent security in the underlying OS is good enough for what those keys are used for.  What is the threat model that you are concerned that someone will get your phone, hack its biometric security, access your ssh key, and then do something bad with it because it doesn't have a separate pass phrase?  Because if you are in a threat enviroment where that is a possibility, then sticking a ssh passphrases on your phone is not going to do much more for you.  There are already a hundred other vectors for an attacker to get what they want and this software is not the answer to your problem.

So for the above reason, the feature you are asking for is not useful to Material Files in addition to the way you are asking for it being unconscionably rude.

**Comment by zhanghai** [comment]
@VA1DER Thank you for speaking up for my experience as the maintainer! I did get upset by demanding users sometimes (espcially when they sound rude even if they didn't intend to, e.g. by saying "unreasonble" or "excuse"), but I tend to ignore such requests instead of trying to argue with them because I don't want to deplete my energy for this project, also because even if my words may be correct, it may sound arrogant to others and spur more controversy. So having a bystander speaking up for me really helps!

Regarding the subject of this issue - I agree that having a password for the private key, when both are stored as clear text (or even encrypted with another baked-in secret key), provides little to no added security, so I would recommend simply decrypting the key before passing it into this app. In modern days the real security barrier should be Android's filesystem security and SELinux, and it should be perfectly fine for the decrypted key to appear as clear text in the app's private data directory. If you are concerned with that, it means you don't trust your device and indeed you should generate a separate key. (There's [Android KeyStore](https://developer.android.com/training/articles/keystore) that provides actual extra security for keys, but I haven't seen any file manager using it so I haven't spent time integrating it as well.)

Note that one doesn't have to generate a new key to get a decrypted key - one can just decrypt their existing key with openssl, and [here](https://www.google.com/search?q=remove+password+from+private+key) are the instructions.

But to avoid the need for the user to run `openssl` manually, and because some other (though not all) file managers also provide a password field, I agree it makes sense for me to trade my time spent on implementing this for everyone else's time when using this feature. So I've tagged this with the v1.5.0 milestone and it is on my list now. If you want to keep track of my roadmap for this app, the milestones page is the right place for it.

**Comment by zhanghai** [comment]
I've updated the strings and uploaded to Transifex - please take a look when you have time. Thanks!
