### ISSUE TITLE
Open MaterialFiles without flashing ⸮⸮⸮ 

### ISSUE THREAD

**Issue by shuvashish76** [zhanghai/MaterialFiles#570]
It not a problem.We can say it's a minor improvement.
When we open MaterialFiles it takes fraction of second to flash white background then it opens up amaze.

There are some apps like WPS office, Librera Pro, VLC, AmazeFileManager etc who open their app without flashing, though they take little amount of time to open. These apps just wait that fraction second & open the app directly.

It would be nice if MaterialFiles open without white flash.

https://user-images.githubusercontent.com/48226312/130378104-573a3dcb-f0b4-4f20-beff-da44634efa18.mp4

**Comment by zhanghai** [comment]
It seems the best solution is to update your system to Android 10 or newer if you care about this experience - the default app theme is already a `DayNight` theme, so if your system is in night mode the initial background should also be dark instead of the white seen in your video.

Waiting for extra time before openning is do-able (`android:windowDisablePreview`) but frowned upon, because it may make users confused about whether they have launched the app or not on slower devices (may take more than 1 second), and unnecessarily impacts the experience of people not using night mode (due to the static nature of Android resource system, day and night mode uses the same initial theme). There are also some other hacks with other drawbacks.

If a system update isn't possible for you, you may also just modify the source code and compile your own APK that disables the window preview - you can add

```xml
        <item name="android:windowDisablePreview">true</item>
```

to https://github.com/zhanghai/MaterialFiles/blob/e05aeeba47f54948d1eaed6fb5304aafbc4222ed/app/src/main/res/values/themes.xml#L10-L12

and then proceed with the APK compilation.

**Comment by shuvashish76** [comment]
https://user-images.githubusercontent.com/48226312/130381213-5d8ac7e2-9425-4c68-a5a0-605aa22ee684.mp4

> There are some apps like WPS office, Librera Pro, VLC, AmazeFileManager etc who open their app without flashing, though they take little amount of time to open. These apps just wait that fraction second & open the app directly.

With 10x slow animation it seems those apps dont wait any such fraction of seconds, they open up instantly. But MaterialFiles does take bit time to load.

I'm not dev sry. The flash screen is not a big problem for me.

🙏🏿Thanks

**Comment by zhanghai** [comment]
There's difference between cold start and warm start - if an app is entirely killed (after reboot or long time inactivity), the first start takes a much longer time and thus the preview window is shown. If the app process is being cached, it can be opened almost instantly without the wait, which seems to be the case in your second video.
