### ISSUE TITLE
Exclude from translation

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#580]
The following text strings should be excluded from the translation and should not appear in Transifex for translators. It only introduces extra work and unnecessary confusion for them, and avoids translation errors.

```
@string/select
@string/preference_copied
@string/edit
@string/file_list_action_copy_path
@string/file_item_action_extract
@string/file_item_action_archive
@string/file_list_action_copy_path
@string/file_list_action_add_bookmark
@string/file_list_action_create_shortcut
@string/storage_edit_smb_server_title_add
@string/ftp_server_title
@string/settings_title
@string/about_title
@string/file_delete_message_file_format
@string/ftp_server_title
@string/storage_list_title
@string/storage_list_empty
@string/settings_bookmark_directories_title
@string/settings_bookmark_directories_summary_empty
@string/navigation_standard_directory_downloads
@string/ftp_server_title
,\u0020
\u0020\u0020\u0020\u0020
%1$d \u00d7 %2$d
%1$.3f, %2$.3f
%1$s %2$s
%1$s (%2$d)
%1$s (%2$s, %3$d)
%1$,d/%2$,d
%1$s
*%1$s
```

You can exclude it by adding `translatable="false"` in `strings.xml`.

**Comment by zhanghai** [comment]
For the string references - My original intention was that although Engilsh reuses another string, translators may choose to localize it differently. But yes, maybe I should just disallow that to avoid confusing translators.

For the rest - They should stay localizable because they are indeed localized differently in some languages. For example, the English comma is half-width, but when localizing in Chinese it should be a full-width comma (`，`) or a different puntuation for parallel relationship (`、`). The same goes for parenthesis and quotation marks, etc.

**Comment by Valdnet** [comment]
> translators may choose to localize it differently

I know from practice that translators do not change paths to another text string 😉.

> My original intention was that although Engilsh reuses another string

Very good idea.

> But yes, maybe I should just disallow that to avoid confusing translators.

Rather, it will be a better solution 😉.
