### ISSUE TITLE
Single and plural text string

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#582]
The following text string should be singular and plural:

`Delete %1$,d items?`

App:
Material Files v1.3.1

**Comment by zhanghai** [comment]
No, it should be plural only because for the singular case the app uses a different string template to show the name of the file being deleted instead.

**Comment by Valdnet** [comment]
@zhanghai What about the number 2? In other languages, "items" is inflected differently for the number 2 and for the number from 5.

Example for the Polish language:

```
Usunąć 2 pozycje?
Usunąć 5 pozycji?
```

**Comment by zhanghai** [comment]
That's an excellent point!

I'll make the string `<plural>` instead of a plain `<string>` to accomodate different languages, in the next version.

However, because the format argument for the single file case is the file name, while the format argument for multiple files is the number of files, I'll still keep them separate to avoid confusion on what the format argument is. i.e. the new `<plural>` will never be used for the `one` case.

**Comment by zhanghai** [comment]
I've updated the strings and uploaded to Transifex - please take a look when you have time. Thanks!

**Comment by Valdnet** [comment]
Thank you. I will translate them today.
