### ISSUE TITLE
[Enhancement] Performance optimization for smb/sftp/content streaming

### ISSUE THREAD

**Issue by bakamosokyo** [zhanghai/MaterialFiles#634]
When streaming to mpv and poweramp from smb/sftp, stutter happens pretty often.
The current cache size is 1s, which is not sufficient.
Increasing cache to 4s or 32MB would be a great improvement.

**Comment by zhanghai** [comment]
Did you actually mean 4MB instead of 4s?

**Comment by bakamosokyo** [comment]
> Did you actually mean 4MB instead of 4s?

Nope, I mean 4s.
By the way, I believe a fixed size like 32MB makes more sense.

**Comment by zhanghai** [comment]
Cache size needs a size unit instead of a time unit. How can you create a SMB transfer cache of 4 seconds?

A bigger cache size like 32MB means the app uses more memory and becomes more likely to be killed, so it's not free of charge. Do you have any test data to support that 32MB is the optimal cache size?

**Comment by bakamosokyo** [comment]
> Cache size needs a size unit instead of a time unit. How can you create a SMB transfer cache of 4 seconds?
> 
> A bigger cache size like 32MB means the app uses more memory and becomes more likely to be killed, so it's not free of charge. Do you have any test data to support that 32MB is the optimal cache size?

### As showed in mpv statistics, the cache is always 1s regardless actual size.
![_20211216_223601 copy](https://user-images.githubusercontent.com/42173719/146382792-32950ce9-43fa-41ce-9026-a8724f01cb36.jpg)

### 32MB is used by cx file explorer, this is the only reason I said 32MB.
![Screenshot_20211216-223837](https://user-images.githubusercontent.com/42173719/146382967-88135fcf-300d-45c1-a8cf-1e5110897e96.jpg)

### Both were streamed using SMB.

**Comment by zhanghai** [comment]
Material Files' SMB implementation won't know if it's a video player or a text editor that's reading a file and obviously can't set a cache based on time. What you've show seems to be a cache inside mpv itself, and I'm not sure how the cache size is determined.

**Comment by bakamosokyo** [comment]
> Material Files' SMB implementation won't know if it's a video player or a text editor that's reading a file and obviously can't set a cache based on time. What you've shown seems to be a cache inside mpv itself, and I'm not sure how the cache size is determined.

Yeah it seems have nothing to do with smb.
So its something about android file handling?
The way files are handled have some difference.

With Material Files, poweramp display file as content://me.zhanghai.android.files.file_provider/smb% (or file% for local files)

With cx file explorer, its http://127.0.0.1:26152/SMB/0/Music/.flac 
(or content://media/external/audio/media/1065 for local files. **And cache in mpv was also 1s in this case.**)

**Comment by bakamosokyo** [comment]
If cache size was set by mpv depending on the type of streaming (content:// or http://), its most likely nothing can be done by Material Files. In that case, I will open a issue in mpv-android.

However, this doesn't explain why poweramp stutters too. perhaps its the fault of something for some reason?

Maybe there is a way to adjust cache size after all, but I'm not a programmer.
Good luck to the developer.

**Comment by zhanghai** [comment]
Actually my assumption is that the cache size shown in mpv is simply/roughly how much it has been able to read ahead. It is a known issue that the SMB and SFTP in this app isn't very fast, so maybe some other tuning in this app can be done (I've already implemented read-ahead buffering for both), but I'm not an expert on these two protocols (I merely read their docs) and actually I don't even personally use them. So maybe we'll need someone to find out how to improve the performance of them in this app.

**Comment by OMTDesign** [comment]
I am glad this issue has been raised. 

I frequently stream videos using both CX file explorer and Material Files. I have just streamed some videos to see the cache varies with each video, but the size is typically under 1MB and always 1second. However my problems have never been due to low cache size.

My problems arise after a few days of using the app, here are some things that I notice:

1. Some videos don't open, or take a very long time to open, independent of which video player is chosen.
2. Some videos can only be watched from start to finish. Any seeking, forward or backwards, will break the streaming.
3. Trying to resume playback of a previously watched video, even if that video played perfectly fine without the aforementioned problems, will fail.

Restarting the app does not fix these issues, however restarting my phone fixes said issues. Could this be a memory leak? I suggest @bakamosokyo restart his phone to see if the stuttering goes away?

**Comment by zhanghai** [comment]
@OMTDesign How did you restart the app? Did you try using "Force stop“ in Settings, which actually stops the app, or did you simply swiped the app away in app switcher?

**Comment by bakamosokyo** [comment]
@OMTDesign 
I didn't have problems you mentioned. 
Something is wrong with your system specifically.
You should open a new issue for this.

The stuttering is definitely a insufficient cache/performance issue for me. 
Again, I doubt this mysterious cache is controlled by material files.

**Comment by bakamosokyo** [comment]
@OMTDesign 

cache problem solved for mpv.
Add these two lines to mpv config.
demuxer-max-bytes=16MiB
demuxer-readahead-secs=4

**Comment by bakamosokyo** [comment]
My specific problems can be solved by increasing cache in individual app.

However, this will not always work.
Improving performance is still important.

Here is the new title:
#### Performance optimization for smb/sftp/content streaming

**Comment by OMTDesign** [comment]
I have forced stopped the app in the past with earlier versions, and it only worked for a short time, while restarting my phone has the app working for days. I ran into the issue a few days ago, but can't remember if I tried to force stop the app. I will have to wait until the issues arise again and to test and see.

**Comment by OMTDesign** [comment]
> @OMTDesign
> 
> cache problem solved for mpv. Add these two lines to mpv config. demuxer-max-bytes=16MiB demuxer-readahead-secs=120

I will try adding these lines when my issues arise to see if it is a problem with MPV or with the Files app. Thanks

**Comment by bakamosokyo** [comment]
> I have forced stopped the app in the past with earlier versions, and it only worked for a short time, while restarting my phone has the app working for days. I ran into the issue a few days ago, but can't remember if I tried to force stop the app. I will have to wait until the issues arise again and to test and see.

@OMTDesign 
The problems you have are very unlikely to be related to mine. 
Neither does it relate to the topic of this specific issue anymore. 
I suggest you to open a new issue instead.

**Comment by zhanghai** [comment]
I tried setting the buffer size in SMBJ's config (`SmbConfig.withBufferSize()`), however setting it to either `64 * 1024` or `4 * 1024 * 1024` resulted in roughly the same spead for copying a file to Windows from my phone, around 1MB/s. The default value is `1 * 1024 * 1024` so I'll keep using that for now.

I also did a trace for CPU usage, and it seems most of the time is indeed spent on network requests.

So I don't have a good idea how to improve the performance here (plus I'm not even an SMB user myself). If anyone can help track down why this is a bit slow I'll be happy to fix, but otherwise I won't be able to improve this.

**Comment by zhanghai** [comment]
It also seems to be dependent on the phone - I re-tested on a Pixel 5 XL, instead of a OnePlues 5, and now I can get >20MB/s download speed. Strange...

**Comment by bakamosokyo** [comment]
> It also seems to be dependent on the phone - I re-tested on a Pixel 5 XL, instead of a OnePlues 5, and now I can get >20MB/s download speed. Strange...

Yeah the specific build config of the kernel for each device could affects a lot of things, way too many.

Though I find MaterialFiles is just slower in terms of pretty much everything, comparing to some other file managers. Even pure local operations are far slower, anywhere between 2-4x. This is also in line with smb/sftp throughput.

I would say this is about something way more fundamental, not certain components.

I'm just a end user obviously, There is nothing I can do to help. 

So I'm closing this issue, good luck.
