### ISSUE TITLE
No video thumbnails in smb shared folder

### ISSUE THREAD

**Issue by Giuseppe5000** [zhanghai/MaterialFiles#683]
When I connect to my samba server I can view the photo thumbnails but not the videos thumbnails

**Comment by Giuseppe5000** [comment]
![smb](https://user-images.githubusercontent.com/32134603/156150757-5edfefde-fbc3-45c1-aae9-c0b43c997905.jpg)

**Comment by zhanghai** [comment]
Unfortunately video thumbnail for SMB files aren't supported.

**Comment by 4ndv** [comment]
@zhanghai Will it ever be supported in the future? I'm using closed-source file managers that able to do so, can you please list things that makes it troublesome to implement, and maybe I'll be able to contribute such feature?

**Comment by zhanghai** [comment]
@4ndv 

1. Which file manager(s) support that?
2. The difficulty is `MediaMetadataRetriever` requiring (parcelable) file descriptors.
3. I'm not accepting code contributions right now, but suggestions are welcome.

**Comment by 4ndv** [comment]
@zhanghai I've been able to find a pretty weird (and interesting) solution:

I've mounted my SMB share via https://github.com/wa2c/cifs-documents-provider and thumbnails appeared! So _technically_ it can be implemented in pure Java/Kotlin, because from the looks of it, cifs-documents-provider also uses smbj and jcifs.

Note about the text below: I'm not a Kotlin, nor Android developer, so everything below is my guesswork.

Looking at MediaMetadataRetriever documentation, from the looks of it, instead of FileDescriptor it can also accept anything that implements MediaDataSource, which only requires `getSize` and `readAt` to be implemented. Maybe that can be somehow glued with jcifs/smbj random access modes 🤔

**Comment by zhanghai** [comment]
Ah yes, I somehow didn't notice that API.

Could you try install and check if the artifact APK in https://github.com/zhanghai/MaterialFiles/actions/runs/6194548147 shows thumbnail for you?

**Comment by 4ndv** [comment]
Nope, no thumbnails :(

**Comment by zhanghai** [comment]
@4ndv Could you please try https://github.com/zhanghai/MaterialFiles/actions/runs/6196623749 ?

**Comment by 4ndv** [comment]
> @4ndv Could you please try https://github.com/zhanghai/MaterialFiles/actions/runs/6196623749 ?

Yes, now it works! Huge thanks! :)

**Comment by zhanghai** [comment]
> Yes, now it works! Huge thanks! :)

Nice, thanks for the confirmation as well!
