### ISSUE TITLE
Some strings do not exist in transifex.com for translation

### ISSUE THREAD

**Issue by eshagh79** [zhanghai/MaterialFiles#724]
Hi, some strings do not exist for translation on transifex.com, but they were translated into Persian anyway. (But they have problems)
The first and Pom strings will appear by holding the finger on the buttons at the top.
The third field is the search box.
None of this string exists on transifex.com.
![new](https://user-images.githubusercontent.com/52137191/160066471-0a91e64e-49c8-4cf8-a30b-984d674547e9.png)
![new2](https://user-images.githubusercontent.com/52137191/160066477-54bab2ed-10dd-4968-8f41-1236246e3757.png)
![new3](https://user-images.githubusercontent.com/52137191/160066485-76480208-a62a-40f4-84c6-ebc6f5975333.png)

**Comment by zhanghai** [comment]
They are part of AndroidX so you need to contribute to that if you think it's wrong - see also https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:appcompat/appcompat/src/main/res/values-fa/strings.xml

**Comment by zhanghai** [comment]
Oh actually, the first one is using the wrong string so I should be able to make it use the right one. But the second and third one do seem to be the expected ones.

**Comment by zhanghai** [comment]
Taken another look at this - the string `nav_app_bar_open_drawer_description` is only in the navigation-ui dependency which this app currently doesn't use and would be redundant if we add dependency on it only for this string. On the other hand, if we don't use it we'll have to introduce our own string, so punting this to v1.5.0.

**Comment by eshagh79** [comment]
I was also surprised to see the first case. Why this translation has been used.
In the second and third cases, their translation is not correct and there is a misspelling.
I will try to correct their translation in the link you provided.

**Comment by Valdnet** [comment]
I did not want to create a new issue, so I will join the conversation on this issue.

@zhanghai I noticed that you have released the new version 1.4.2, but you have not downloaded the Transifex translations which were corrected by me in Polish. I cannot validate them directly in the application.
Second, I think you should systematically update new text strings for Transifex so that translators can translate on the fly. It is not a good idea to send text strings just before a new version is released, as not all translators will have time to translate them in such a short time.

**Comment by zhanghai** [comment]
Since v1.4.2 is an urgent patch release and only two days from v1.4.1, I didn't import translations this time.

I've saw your comment at https://github.com/zhanghai/MaterialFiles/issues/213#issuecomment-1068005414 and I'll do the translation upload when the FTP client feature is finalized. The next release v1.5.0 is expected to be months later so no need to hurry :P
