### ISSUE TITLE
Background Battery Consumption

### ISSUE THREAD

**Issue by s4nket** [zhanghai/MaterialFiles#725]
Material Files is consuming battery in the background even after enabling battery optimization, force stopping and uninstalling it.
How do i kill this process?
![Screenshot_20220326-101939.jpg](https://user-images.githubusercontent.com/29552731/160225139-8cd3d87c-5363-4f11-87e5-98de0b91e074.jpg)
This graph is from last night after I uninstalled the app, this is happening since yesterday evening.

**Comment by zhanghai** [comment]
That's so weird. I don't think an app can still work or consume battery even after you uninstalled it, so it's either your device attributing the power consumption incorrectly, or you discovered a highly severe security bug.

Since this app is completely open-source you can also individually verify there's no such code trying to do that, so I think it's more likely your system just displayed the wrong app.

**Comment by s4nket** [comment]
Rebooting seems to have fixed the issue, thanks.
![Screenshot_20220322-124548.jpg](https://user-images.githubusercontent.com/29552731/160229499-60618690-332d-4e51-8e01-5b52da0187a7.jpg)
