### ISSUE TITLE
[Unacceptable Feature Request] Visual Classification of Data upon opening app

### ISSUE THREAD

**Issue by pixincreate** [zhanghai/MaterialFiles#759]
![Screenshot_20220416-141401_File_Manager](https://user-images.githubusercontent.com/69745008/163669319-5cdbc3eb-ed29-4b4d-a4ae-8d4223584ccd.png)

Above image clears about what I'm talking about.

An option to access different file types in mass would be helpful. I'm aware of the fact that this will be rejected but I wanna ask. Swipe up expands internal storage and usual Material Files.

What's your thought on this?

**Comment by zhanghai** [comment]
Well, you are right that this would go against the model of this app so it won't be accepted. However the design does look nice - just curious, what app is it?

**Comment by pixincreate** [comment]
The UI interface showed is Asus file manager taken from @Ayraproject on Telegram. 

My proposal was that, when a user opens the app, he is supposed to be greeted with those 9 icons and small line of internal storage. On swiping up, usual Material File Manager opens up.

Wouldn't that be interesting?

**Comment by zhanghai** [comment]
Ah I see, it's made by ASUS for their phones, thanks for the info. I was only finding the design polished & interesting though, but not the idea, because for myself I never used most of the things listed in that screenshot (including those 9 icons). If you want that I think Google's Files Go might be a more apropriate alternative than this app.
