### ISSUE TITLE
Feature Request (Remove query_all_packages)

### ISSUE THREAD

**Issue by GithubContributor832** [zhanghai/MaterialFiles#807]
I find this very violating as it lets the app see all installed apps. As far as I'm aware you don't collect it but it be a huge privacy plus on all versions if it was removed. I know analytics are removed thankfully on Fdroid. Regardless this is incredible work I use gladly but if this permission was removed it be a privacy tank.

**Comment by zhanghai** [comment]
It's used for showing the app icons for directories named after package names.

If you are using the F-Droid version, the app is built from GitHub source code by F-Droid server and signed by F-Droid key, and as you mentioned any proprietary code is removed (even RAR support) due to F-Droid policy, so one can be sure that no data is ever collected or uploaded, and there will be no plus for privacy because there's already nothing to improve.

So I don't think it's reasonable to remove QUERY_ALL_PACKAGES and break the functionality for other people. If one still insists that the permission should be removed, I believe they are still free to run their own build and remove the permission in that process.

**Comment by GithubContributor832** [comment]
Thanks for the soothing info. I understand but it be great if you could find away around this permission. However, I still run the Fdroid version glad and am ok without RAR support as Zarchiver without internet permission crushes it. Thanks again for the response and all your hard work.
