### ISSUE TITLE
MaterialFiles "data" directory withOUT root

### ISSUE THREAD

**Issue by mmm4m5m** [zhanghai/MaterialFiles#814]
Thank you for this application!

Why I can not browse the application "data" directory withOUT root?

It could be useful to hide some files there (without root).

There is also Secure-File-Manager application... but (I think) your application have more build-in file viewers (for images, text files).

Do you think it is good idea for a new feature?

In case you like the idea, there is one more thing (which is missing in Secure-File-Manager application):
"Hide file" behaviour similar to "Trash" delete/restore:
1) on hide file - move file to application "data" directory and preserve dir tree; 
2) on unhide file - restore to the original location

**Comment by mmm4m5m** [comment]
@zhanghai

Add storage "Android/data" is showing the internal storage "Android/data" dir.

My question is about "/data/data/me.zhanghai.android.files" dir (with 'cache', 'code_cache', 'shared_prefs'). And sub-dir inside 'Hidden'.

As far I know... Before Android 11, dir "Android/data" is visible for all aplications. After Android 11, it is again visible for all applications which get permission "all files"... That is why it is not actually "hidden" location.

**Comment by zhanghai** [comment]
I see. If you are talking about `/data/data/me.zhanghai.android.files`, you can go there by setting root access mode to never inside app settings, and then use the Go to menu option. The default is automatic which asks for root even for `/data/data/me.zhanghai.android.files` because there are certain things you can't do without root access, so to avoid the confusion of the directory seemingly fully accessible but actually not, you need to change that setting to make sure you are opting out of full access.

**Comment by mmm4m5m** [comment]
Thank you! :)

**Comment by russianbot91** [comment]
This can be done without root using the storage access framework. FV File Explorer (Closed Source) does it this way.
