### ISSUE TITLE
Android 13 support

### ISSUE THREAD

**Issue by basings** [zhanghai/MaterialFiles#852]
Material Files does not work under Android 13. It's impossible to grant it to manage all files.

**Comment by zhanghai** [comment]
Works fine for me, please provide more details on why it's impossible.

**Comment by basings** [comment]
I can't tap on any field. 
![Screenshot_20220904-192705~2](https://user-images.githubusercontent.com/92867705/188325960-06755e50-ac33-4e19-801e-74494fdf5237.png)

And in the general settings,  the permission isn't even listed. 
![Screenshot_20220904-192926~2](https://user-images.githubusercontent.com/92867705/188326020-f373e0b2-04a7-4993-a829-79e14c027416.png)

- Pixel 6, grapheneos, Android 13
- material files v 1.5.2

**Comment by zhanghai** [comment]
The reason you are unable to click any of the options is probably that you have some screen overlays and thus the system dialog didn't allow you to click it for security reasons. If you remove the overlays it should work again.


The dialog you shown is not part of standard Android and should be part of GrapheneOS, so I don't know what's wrong with it either. Normally you should be able to manually allow the access at `Settings > Apps > Special app access > All files access`, but I can't guarantee it to work for GrapheneOS either because they have non-standard customizations.

**Comment by FastenM** [comment]
Android 13 removed the bypass/loop to access the android/data & android/obb file paths by hooking into the internal files app from android
(Non root phones)
I wish someone finds a new way on how to grant access to those file paths 

Maybe it's possible with adb???

**Comment by zhanghai** [comment]
I assume you were able to grantt the All files access, and are now talking about a different issue now. I see you already commented on the other bug that's actually about it.

**Comment by basings** [comment]
@zhanghai Thhank you for having a look into the issue. Your comment solves the issue. Sorry for bothering you, it was obviously my fault without realizing it. And a bug of grapheneos that resets permissions after the update. But it's still unclear to me why there's no permission given in the settings, that's strange.
